#!/usr/bin/python3
from sys import argv
import math



def factory(num):

    if num % 2 == 0:
        x = 2
        print("{}={}*{}".format(num, int(num//x), x))
    else:
        jj = int(math.sqrt(num)) + 1
        for x in range(3, jj, +2):
            if num % x == 0:
                print("{}={}*{}".format(num, int(num//x), x))
                return
            if num % (jj + x) == 0:
                print("{}={}*{}".format(num, jj + x, int(num//(jj + x))))
                return
            if num % (jj - x) == 0:
                print("{}={}*{}".format(num, jj - 1, int(num//(jj - x))))
                return

def factors(filename):
    with open(filename, encoding="utf-8") as my_file:
        for x in my_file.readlines():
            z = int(x)
            result = factory(z)


if __name__ == "__main__":
    factors(argv[1])
